- name: database container
  docker_container:
    name: database
    image: marthemouah/devop_tp2-main_database
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_DB: db
