language: java
jobs:
  include:
    - stage: test
    script: mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install
        sonar:sonar -Dsonar.projectKey=devop_tp2
    - stage: test
     script: docker login -u $dockerhub_id -p $dockerhub_pwd
    - stage: test
     script: docker build -t $dockerhub_id/devop_tp2-main_database database
    - stage: test
     script: docker build -t $dockerhub_id/devop_tp2-main_httpd httpd
    - stage: test
     script: docker build -t $dockerhub_id/devop_tp2-main_simple-api simple-api

    - stage: publish
     script: docker push $dockerhub_id/devop_tp2-main_database
    - stage: publish
     script: docker push $dockerhub_id/devop_tp2-main_httpd
    - stage: publish
     script: docker push $dockerhub_id/devop_tp2-main_simple-api

cache:
  - $HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "Marthe-p"
    token: "$SONARCLOUD_TOKEN"
