language: java
script:
  - mvn clean verify --file ./simple-api/pom.xml

  - docker login -u $dockerhub_id -p $dockerhub_pwd

  - docker build -t marthemouah/devop_tp2-main_database database
  - docker build -t marthemouah/devop_tp2-main_httpd httpd
  - docker build -t marthemouah/devop_tp2-main_simple-api simple-api

  - docker push marthemouah/devop_tp2-main_database
  - docker push marthemouah/devop_tp2-main_httpd
  - docker push marthemouah/devop_tp2-main_simple-api
  cache:
  directories:
    - $HOME/.m2
  services:
    - docker
