language: java
stages:
  - test
  - build
  - push

jobs:
  include:
    - stages: test
      name: test
      script: mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Marthe-p_devop_tp2
      if: branch = dev

    - stages: build
      name: build
      script:
        - docker login -u $dockerhub_id -p $dockerhub_pwd
        - docker build -t $dockerhub_id/devop_tp2-main_database database
        - docker build -t $dockerhub_id/devop_tp2-main_httpd httpd
        - docker build -t $dockerhub_id/devop_tp2-main_simple-api simple-api
      if: branch = dev

    - stages: push
      name: push
      script:
        - docker push $dockerhub_id/devop_tp2-main_database
        - docker push $dockerhub_id/devop_tp2-main_httpd
        - docker push $dockerhub_id/devop_tp2-main_simple-api
      if: branch = main
cache:
  directories:
    - $HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "marthe-p"
    token: $sonarcloud_token
